### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by Vahe1994** [guohaoxiang/ComplexGen#1]
Hello! I was very excited to read your paper. It is awesome work! 
Although, I have a little trouble downloading from pan.Baidu.  It seems pan.baidu not working for overseas countries. It would be great, if you could provide additional link, to other storage cloud service (for example Google Drive), to have access from other countries as an alternative. 
Thank you!

**Comment by guohaoxiang** [comment]
Thanks for your advise! OneDrive download link has been added :-）

**Comment by Vahe1994** [comment]
Thank you for fast response and for adding one drive link. You are awesome!
