### ISSUE TITLE
About data cleaning

### ISSUE THREAD

**Issue by Mingyu-Zheng** [guohaoxiang/ComplexGen#11]
Hi and thank you for the great work!
May I ask if you could provide the code you used in the data cleaning process? I saw your data cleaning steps in the supplementary materials, but I don't know how operations are achieved, like "Parametric representations of patches do not match their discrete mesh representation" or "Over-segmentation of patches (curves) by junctions whose neighboring patches (curves) have identical types and geometry".

**Comment by guohaoxiang** [comment]
I've checkout from MSRA and this part of code is missing, sorry for the inconvenience.
"Parametric representations of patches do not match their discrete mesh representation": For example, the parametric representation of a sphere is (x-c)^2 = r where c is its center and r is its radius. You can also get the exact triangle mesh of the sphere from the ABC *.yml file. If the points in the triangle mesh do not satifies (x-c)^2 = r, we will treat the model invalid and abandon it.

"Over-segmentation of patches (curves) by junctions whose neighboring patches (curves) have identical types and geometry":
![image](https://user-images.githubusercontent.com/29721619/232365816-dcc720e9-ea78-4b69-b364-f3c56fdf8e48.png)
For example, the two red dashlines split the cylinder into two patches, and those two patches share the same parametric representations, in this case we will remove these two dashlines

**Comment by Mingyu-Zheng** [comment]
Thanks! And what about "Disconnected components in one model. The components frequently overlap spatially, leading to self-intersecting and ambiguous models"? How can we judge whether a model is self-intersecting or ambiguous?

**Comment by guohaoxiang** [comment]
For CAD models with several disconnected components (e.g. a cylidner and a cube which share no common faces), we split the model to several connected component. For each connected component, we use CGAL to judge whether the triangle mesh is self-intersected. All models with self intersection are removed from the dataset.

**Comment by Mingyu-Zheng** [comment]
Thank you! I noticed that there is a sub-index in the ID of some samples in your dataset, such as 00861147_0, 00861147_1, and 00861147_2. This seems to refer to the several components separated from the sample 00861147. How is the order of these components (0, 1 or 2) determined?

**Comment by guohaoxiang** [comment]
We sort the components of a model according to the number of its vertices in descending order.

**Comment by Mingyu-Zheng** [comment]
Thanks a lot! I will have a try.
