### ISSUE TITLE
Where is the file packed_000000.pkl_10000.ply used in GeometricRefinement?

### ISSUE THREAD

**Issue by MartensCedric** [guohaoxiang/ComplexGen#12]
I followed the steps to get the this default object using the pre-trained model. I'm stuck at the step

`python .\scripts\geometric_refine.py`

As it requires a point cloud

` what():  PLY parser: Could not open file data/default/test_point_clouds/packed_000000.pkl_10000.ply`

If I ignore this step I can still get the .obj, just of lower quality.

![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/6fa293e3-cf37-40a6-9b23-b1bb3b6111b6)

![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/ad6f7afe-dbfb-4b14-bd7d-10106d722e03)

This is the line I ran to get the .obj file:
`python gen_vis_result.py -i ../experiments/default/test_obj/packed_000000.pkl_extraction.complex`

I expected to find a file named `packed_000000.pkl_10000.ply` somewhere in the .zip from onedrive but I cannot find this file. 

In the folder `default\data\default\test_point_clouds\` and sorting alphabetically, I can find

![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/1e286a68-03cf-4deb-8059-e5427cde3e60)

And in reverse alphabetical order

![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/5fd9ddcd-b886-4463-8842-433de21cb811)

Do you have instructions on how to obtain this file?

[packed_000000.pkl_extraction.obj.zip](https://github.com/guohaoxiang/ComplexGen/files/11436935/packed_000000.pkl_extraction.obj.zip)

**Comment by guohaoxiang** [comment]
Hi Cedric, how do you get the file named "packed_000000.pkl_extraction.complex"? This is abnormal. After conducting the [Complex Extraction](https://github.com/guohaoxiang/ComplexGen/tree/main#phase-2-complex-extraction) step, you should get files named like "00860007_0_extraction.complex", then "geometric_refine.py" will find the corresponding "00860007_0_10000.ply" and use it for computing.

**Comment by MartensCedric** [comment]
Hi, I'm not sure how I got there but I'm starting back from the beginning now. I guess It's because I had forgotten to run the complex extraction step. 

I would like to eventually run my own point cloud so I've read issues #3, #7 and #10. Before even doing that I would like to test the code on a single point cloud but I'm not sure if I'm doing it correctly as the output is different than I had imagined. Here are my steps.

0. I deleted the folders `log`, `obj` and `test_obj` under `experiments/default`

1. I created a directory: `data/default/our_test/packed/` 

2. I copy pasted the `packed_000000.pkl` (4GB) from `train_small` obtained on onedrive into my directory `data/default/our_test/packed`.

3. I verified that this file only contains a single point cloud (data['surface_point'] contains 10000 points of size 6).

4.  I modified the file `Minkowski_backbone.py` on line 4091 to

`test_folder = os.path.join(base_folder, "default/our_test")`

5. I ran `./scripts/test_default.sh`

What I expected: To find a single pkl file with the prediction inside of the `experiments/default/test_obj/` folder.
What I got: 3k+ files inside of  `experiments/default/test_obj/`

**Question 1**: Is this abnormal? I only want to run 1 pointcloud and get the impression is ran for 3k point clouds.

6. I make sure the flag_parallel=False since I just want to run on 

>  As the average extraction time for each model is 10 minutes, we recommend you to conduct complex extraction on a multi-thread cpu server.

Since my goal is to just run it for a single model. I did not expect for this to take long but clearly it seems like it's 10 mins per pkl file and I have 3000, not 1. I stopped after three models and I have these files. 


```
00889323_0_extraction.complex
00889323_0_prediction.complex
00889323_0_prediction_timing.txt
00911730_0_prediction.complex
00937591_0_extraction.complex
00937591_0_prediction.complex
00937591_0_prediction_timing.txt
default.mtl
test_sample_name.txt
test_statistics.txt
test_statistics.xlsx
cedric@BOKCHOY:~/Programming/complexgen/experiments/default/test_obj$ ls | grep -v pkl
```

7. Now I run `python scripts/geometric_refine.py`, it complains that it's missing `test_point_clouds` data

**Question 2**: Why is there a need for test_point_clouds data? From my understanding the input should be a point cloud and now we are at stage 3.

8. I fix the missing `test_point_clouds` data by simply placing the folder in `data/default/test_point_clouds` and run

 `python scripts/geometric_refine.py`
 
 I now observe patch .obj files that appear at the root of my project
![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/81e71779-0581-426c-afd6-13e8c8ac05dc)

And I also have more complex files:

```
00888206_0_extraction.complex
00888206_0_prediction.complex
00889323_0_extraction.complex
00889323_0_prediction.complex
00911730_0_extraction.complex
00911730_0_prediction.complex
00913120_0_prediction.complex
00936016_0_extraction.complex
00936016_0_prediction.complex
00937591_0_extraction.complex
00937591_0_prediction.complex
root@BOKCHOY:/workspace/experiments/default/test_obj#
```

9. I copy the complexgen.mtl file: `cp complexgen.mtl ../experiments/default/test_obj/`

10. I run the gen vis on all the complex files: 

``root@BOKCHOY:/workspace/vis# for f in `find ../experiments/default/test_obj/ -name "*.complex"`; do python gen_vis_result.py -i $f; done``

I now have `.obj` files:

```
00888206_0_extraction.obj
00888206_0_prediction.obj
00889323_0_extraction.obj
00889323_0_prediction.obj
00911730_0_extraction.obj
00911730_0_prediction.obj
00913120_0_prediction.obj
00936016_0_extraction.obj
00936016_0_prediction.obj
00937591_0_extraction.obj
00937591_0_prediction.obj
```

I open a few:

![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/614776d2-132e-49c6-b04c-7f9a29c3fed0)

![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/e98f6f0f-5a0c-4015-9946-aab924521683)
![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/f31a5773-7f16-4a69-a3d0-804534dbfc20)


Question 4: Now clearly, these objects are from different point clouds, how did I end up with multiple objects if I intended to input a single point cloud?

Thank you so much for your time, I hope this detailed message helps understanding what I did wrong

Here's my results
[cedric.zip](https://github.com/guohaoxiang/ComplexGen/files/11456263/cedric.zip)

**Comment by guohaoxiang** [comment]
Question 1: Is this abnormal? I only want to run 1 pointcloud and get the impression is ran for 3k point clouds.
A1: The 'packed_000000.pkl' is not about a single shape, indeed it contains the information of 3000+ shapes. Each time you conduct 'data = pickle.load(pkl_file)',  the information of a new shape will be stored in 'data'.

Question 2: Why is there a need for test_point_clouds data? From my understanding the input should be a point cloud and now we are at stage 3. 
A2: The 'test_point_clouds' indeed stores the input point cloud in ply format. In stage 3, we still need the input point cloud as reference when conducting shape optimization.

(I do not find Question 3)
Question 4: Now clearly, these objects are from different point clouds, how did I end up with multiple objects if I intended to input a single point cloud?
A4: See A1.

**Comment by MartensCedric** [comment]
> Each time you conduct 'data = pickle.load(pkl_file)', the information of a new shape will be stored in 'data'.

I did not know this! Thank you for the prompt and precise responses!
