### ISSUE TITLE
Tips on improving partial results

### ISSUE THREAD

**Issue by MartensCedric** [guohaoxiang/ComplexGen#13]
Hello,

I would like to know if there are tips to improve our results on this model.

![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/68d8165c-345d-47d5-b688-4807539edd38)

![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/82035e4e-fb61-4dfc-80ce-5bb9f0a309b9)

I have followed the steps as we discussed yesterday in #12 but using the `partial` checkpoint since our data is incomplete.

![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/5da6ca38-8e19-4907-986c-d7963ee4a3e2)
![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/1a7f27f1-5e34-4fa9-8550-c55e4e8f354b)

I would like to know if this is the best we can do without training.  I know that trimming isn't performed due to numerical instability as discussed in a previous issue.

Also note that I was not able to perform geometric_refinement.

```
cedric@BOKCHOY:~/Programming/complexgen$ python scripts/geometric_refine.py
00953239_0_extraction.complex
corner: 27 curve: 45 patch: 21
patch close: 0
patch close: 1
patch close: 0
patch close: 0
id: 3 flip uv: 0
patch close: 0
patch close: 0
patch close: 0
patch close: 0
patch close: 0
patch close: 0
patch close: 0
patch close: 1
patch close: 1
patch close: 0
patch close: 0
patch close: 0
patch close: 1
patch close: 0
id: 17 flip uv: 0
patch close: 0
patch close: 1
patch close: 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  PLY parser: Could not open file data/partial/test_point_clouds/00953239_0_10000.ply
Aborted (core dumped)
```

So I just skipped this step. (I made very sure I performed `test_partial.sh` and then `extraction_partial.sh`). I had fixed this error by downloading the .ply from the OneDrive but they 
are not available for the `partial/` folder.

I have attached our original .ply, the pointcloud inside of a .pkl and the results in a .zip
[to_complexgen.zip](https://github.com/guohaoxiang/ComplexGen/files/11468103/to_complexgen.zip)

**Comment by guohaoxiang** [comment]
Without geometric refinement, your result seems normal. You can conduct geometric refinement by replacing the path  "data/partial/test_point_clouds/00953239_0_10000.ply" with your point cloud.

**Comment by MartensCedric** [comment]
Ok thanks! After converting my pointcloud to ply and placing it there I was able to get these better results. Thank you 
![image](https://github.com/guohaoxiang/ComplexGen/assets/18620025/23ef4cf3-dcd0-4fc4-92d9-126becb6abe6)
