### ISSUE TITLE
Is the input model normalized on each axis individually?

### ISSUE THREAD

**Issue by yilinliu77** [guohaoxiang/ComplexGen#15]
Thanks for sharing the code with us. I have a question about the normalization process.

I saw that the input point cloud had been normalized into [-0.5,0.5]^3 in each axis **individually**. Does that make sense? The resulting point cloud after normalization will be somehow flattened. For example, a cylinder might be an elliptical cylinder.

However, the network still predicts it as a cylinder. But it doesn't know the actual shape before the normalization. Will that mean that no matter how elliptical the input point cloud is, the network will constantly predict it as a cylinder?

**Comment by guohaoxiang** [comment]
For each model, the scaling step is apply to all axis **uniformly**, please check the following codes for detail:
https://github.com/guohaoxiang/ComplexGen/blob/af8f336ea46f795da740bebdfb1da1d573dd3789/data_loader_abc.py#L43C13-L43C13

**Comment by yilinliu77** [comment]
Oh, ok, I get it. Thanks for your quick reply!
