### ISSUE TITLE
Instructions Link on how to build Geometric refinement project is invalid

### ISSUE THREAD

**Issue by homo-iocus** [guohaoxiang/ComplexGen#17]
In the readme you mention a link to a instruction on how to build the Geometric refinement part on Linux. 
However the link provided isn't valid anymore - the page is not found.

Could you please update the link or the readme with the instructions on how to compile under Linux?

Thanks a lot!

**Comment by guohaoxiang** [comment]
hi, you can refer here:
https://github.com/Mingyu-Zheng/mingyu-zheng.github.io/blob/master/_posts/geometric-modeling/2023-2-12-%E3%80%8CCAD%E5%AE%9E%E4%BD%93%E5%BB%BA%E6%A8%A1%E3%80%8DComplexGen%E5%87%A0%E4%BD%95%E4%BC%98%E5%8C%96%E9%85%8D%E7%BD%AE.md

**Comment by homo-iocus** [comment]
Thank you very much for the fast response. Very helpful!
