### ISSUE TITLE
sphere_94.obj

### ISSUE THREAD

**Issue by Vahe1994** [guohaoxiang/ComplexGen#2]
Hello!
I'm trying to visualize file "from output of each phase" files. In the gen_vis_result.py file in  complexjson_to_obj, load_obj_simple were called for 'load sphere_94.obj' file ( line 250). I could not find this file anywhere. Without this file, I could not visualize json file from your outputs. What can be done ? 
P.s.1 In line 291 and 298 gen_vis_result.py file, I got  error "AttributeError: 'list' object has no attribute 'shape'".
P.s.2   In docker creation for Phase 1, apt-get update command may get error(4 line). To solve this problem, command "rm /etc/apt/sources.list.d/cuda.list" can be used from here https://github.com/NVIDIA/nvidia-docker/issues/619. 
Thanks, Vage

**Comment by guohaoxiang** [comment]
Thanks, Vage! sphere_94.obj already uploaded in folder 'vis'.
