### ISSUE TITLE
Preprocessing point cloud ply file into pkl file

### ISSUE THREAD

**Issue by eunzihong** [guohaoxiang/ComplexGen#3]
Hi and thank you for your great work!

I recently came across your work and am trying to build upon your code.

For testing, I want to test my point clouds .ply files.
But the dataset loader seems requiring prepreocessed .pkl files for that.

Can you tell me how to make pkl file from point cloud .ply files?

Regards,
Eunji.

**Comment by guohaoxiang** [comment]
Hi Eunzi,
Thanks for your interests on our work.
The preprocessed .pkl files are indeed a dictionary containing the  point cloud and parametric information of one input shape. To test your own point clouds, please conduct the following step:
1. normalized your data within the bounding box [-0.5, 0.5]^3
2. load ./data/train_small/train/packed/packed_000000.pkl in python to a dictionary. Say the dictionary is called 'data', now 'data['surface_points']' should be an array of shape [10000, 6], corresponding the position and normal of a point cloud. Please replace it with your own point cloud.
3. Dump 'data' to another .pkl file.
```
input_file = open('packed_000000.pkl', 'rb')
output_file = open('output_pickle.pkl', 'wb')
sample = pickle.load(input_file)
sample['surface_points'] = YOUR_OWN_NUMPY_POINT_CLOUD
pickle.dump(sample, output_file)
output_file.close()
input_file.close()
```

4. Put the dumped file under a folder called 'packed', modify 'test_folder' in the following line to the folder containing your 'packed' folder. (Please make sure that 'packed' folder does not contains any other files)
https://github.com/guohaoxiang/ComplexGen/blob/8f53b855c5612df85220e00fd165bc5d445e7b02/Minkowski_backbone.py#L4091

5. run './scripts/test_default.sh'

**Comment by eunzihong** [comment]
Hi, Haoxiang

Thank you for your answer 👍
I'll try it right away!

Best,
Eunji

**Comment by Tomoki-0526** [comment]
Hi, Haoxiang
Thanks for your great work and I wonder if 'data_list[0]['surface_points']' must be an array of shape [10000, 6] for a point cloud has usually more than 10000 points.

**Comment by guohaoxiang** [comment]
> Hi, Haoxiang Thanks for your great work and I wonder if 'data_list[0]['surface_points']' must be an array of shape [10000, 6] for a point cloud has usually more than 10000 points.

I think it will work, as all point clouds will be converted to sparse voxels in the later stage.
