### ISSUE TITLE
Input .ply format in "Phase 1: ComplexNet prediction"

### ISSUE THREAD

**Issue by Mingyu-Zheng** [guohaoxiang/ComplexGen#5]
Hello, I'm trying to run your code. 

I built the environment with reference to the configuration in `README.md` and successfully ran the **"Phase 1: ComplexNet prediction"**. I noticed that in the test script provided, the network input is in the `.pkl` format, which contains some information beyond the `.ply` format point cloud(line, patch_points, etc). I want to ask whether the input in the `.ply` format is supported? (I noticed that your `output_data` includes `_input.ply`, but I didn't find this part in the code.)

**Comment by guohaoxiang** [comment]
Please refer to this issue: https://github.com/guohaoxiang/ComplexGen/issues/3
