### ISSUE TITLE
A ValueError in visualization of .complex file

### ISSUE THREAD

**Issue by Tomoki-0526** [guohaoxiang/ComplexGen#6]
Thanks for your great work!

I come across a problem running your code. When I execute "./scripts/extraction_default.sh" there is a value error reporting the incorrectness of dimension.
![屏幕截图 2022-12-12 133852](https://user-images.githubusercontent.com/73088234/206971257-4c0bdc01-655f-4bb3-b469-ee8f0af87cae.png)
I really wonder how to solve it, looking forward to your help.

**Comment by guohaoxiang** [comment]
Hi, can you send the 00860007_0_prediction.complex file to me?

**Comment by Tomoki-0526** [comment]
Actually I find several files that all have similar problem, here is the zip file.

[1.zip](https://github.com/guohaoxiang/ComplexGen/files/10205207/1.zip)

And further more there may be some .complex files (such as 00860128_0_prediction.complex) that successfully run through the extraction module but the result is totally different from the original .ply file. If it's convenient can you please also take a look at this one? The .ply and .complex file are in 2.zip. Thanks a lot!
[2.zip](https://github.com/guohaoxiang/ComplexGen/files/10205220/2.zip)

**Comment by Tomoki-0526** [comment]
Sorry I mean the visualization part, not extraction...

**Comment by guohaoxiang** [comment]
Hi, Tomoki, I've upload a new version of gen_vis_result.py, which can deal with your issue. But it seems that the complex files you provide here are just a random set of points, curves and patches. You can use the correct version of .complex files, which can be download from here: https://github.com/guohaoxiang/ComplexGen#data-downloading.
