### ISSUE TITLE
Different point clouds generate same obj file

### ISSUE THREAD

**Issue by ghost** [guohaoxiang/ComplexGen#7]
Hi Haoxiang, I tested my point clouds using your work but found all input point clouds turn into same *.obj file.

[obj.zip](https://github.com/guohaoxiang/ComplexGen/files/10356800/obj.zip)

I guess it's because of the method you mentioned in issue #3 which is also a question for me. It says replace the content in 'data_list[0]['surface_points']' with my own point cloud, but other fields in data_list[0](curves, patches and filename) are not covered so I didn't modify these parts. I wonder whether my incorrect outputs are related to this and how to deal with the problem.

Thanks!

**Comment by guohaoxiang** [comment]
Hi Eusford, in the inference stage, only the 'data_list[0]['surface_points']' fields are used, data_list[0](curves, patches and filename) are used for training. Does your input include point normals? Have you normalized the input points?

**Comment by ghost** [comment]
Ok I find there was something wrong with my normalization for I didn't completely scale the box into [-0.5, 0.5]^3. 

But when I run again the code with the correct point cloud, the results are still very similar(in fact they are so strange and messy). 
![屏幕截图 2023-01-11 154713](https://user-images.githubusercontent.com/44888183/211747677-5f4929f4-9f87-4934-bb61-e9e3ffdb01d9.png)

I put 6 different point clouds into a packed pkl file, and I find the outputs of Phase 1 are already the same for all 6 inputs. I think I did the correct preprocess, so maybe the core of the problem is not the normalization?

Here are my packed *.pkl file, the outputs of prediction, and the log.
[lol.zip](https://github.com/guohaoxiang/ComplexGen/files/10389979/lol.zip)

**Comment by guohaoxiang** [comment]
I notice that the input 'packed_000000.pkl' is a dictionary, not a list. Please exactly follow the steps mentioned in issue #3 to prepare the input.

**Comment by ghost** [comment]
This is the url of present packed *.pkl file that I think is correct with its outputs. But the final results are also like the image above :(.
https://drive.google.com/file/d/13EIMDuwrCNSkKu-7h2rKpzMLtER1KYYB/view?usp=sharing.

**Comment by guohaoxiang** [comment]
I have no permission to visit the url. Have you tried my provided input data, are the results normal?

**Comment by ghost** [comment]
I've updated my access right and you can visit the url now. And the results of your provided data are normal.

**Comment by guohaoxiang** [comment]
Hi, Eusford. I checked your provided data and found that the input point cloud is rather challenging, cause it contains large missing areas with random noise on the surface.
![image](https://user-images.githubusercontent.com/29721619/215250506-ce7f616c-6f9f-4a5e-936a-dcc88e4e1f66.png)

You can tried to reconstruct the point cloud with the noisy/partial version of checkpoint. As there is a significant difference between your provided point cloud and my prepared dataset, I don't think the reconstructed result will be ideal. If you want to use our pipeline to process your data, a better way is to re-train the network with your own dataset.

**Comment by ghost** [comment]
Thanks for your suggestion but I still wonder why different inputs lead to same output, I will try the noisy/partial version of checkpoint first!

**Comment by ghost** [comment]
Noisy/partial version still generated 6 *.pkl files with the same size of 725,596 bytes, similar to the results in the url. Can you please check if my input packed file is valid?

**Comment by guohaoxiang** [comment]
As I said earlier, after loading 'packed_000000.pkl' with:
```
f = open('packed_000000.pkl', 'rb')
data = pickle.load(f)
```
I found that variable 'data' is a dictionary, not a list. Please exactly follow the steps mentioned in issue https://github.com/guohaoxiang/ComplexGen/issues/3 to prepare the input.

**Comment by ghost** [comment]
I tested the original *.pkl files you provide but found that all the variables 'data' are indeed a dictionary, not a list.
In fact If I dumped 'data_list' into the *.pkl files, it would report a TypeError as follows. Therefore, I must dumped 'data_list[0]' so that the 'data' variable became a dictionary. Other than this point I examined the steps in issue #3 and I'm sure there were no problems.

```
Traceback (most recent call last):
  File "Minkowski_backbone.py", line 4582, in <module>
    eval_pipeline()
  File "Minkowski_backbone.py", line 4101, in eval_pipeline
    train_data = train_data_loader(args.batch_size, voxel_dim=voxel_dim, feature_type=args.input_feature_type, pad1s=not args.backbone_feature_encode, rotation_augmentation=args.rotation_augment, with_normal=args.input_normal_signals,  data_folder=test_folder, with_distribute_sampler=False, flag_quick_test=args.quicktest, flag_noise=args.noise, flag_grid = args.patch_grid, flag_patch_uv=args.patch_uv, dim_grid = points_per_patch_dim, eval_res_cov = args.eval_res_cov)
  File "/home/szj/ComplexGen/data_loader_abc.py", line 622, in train_data_loader
    pack_pickle_files(data_folder, os.path.join(data_folder, "packed"))
  File "/home/szj/ComplexGen/data_loader_abc.py", line 35, in pack_pickle_files
    sample['filename'] = file
TypeError: list indices must be integers or slices, not str
```

**Comment by guohaoxiang** [comment]
That's a bit strange. Since the output of my provided data is normal, maybe you can try to directly change the 'surface_points' of the provided data to your own point cloud and check the output. (I recommend you to subsample your point cloud to 10,000 points).

**Comment by ghost** [comment]
OK! Maybe I should build your code and try your original data again from the beginning, then check my own inputs. Thanks for your help and sorry to bother you for such a long time!

**Comment by guohaoxiang** [comment]
Hi, Euford. I've update the data processing procedure in https://github.com/guohaoxiang/ComplexGen/issues/3, maybe it will help you.
