### ISSUE TITLE
About generating the ground truth data. 

### ISSUE THREAD

**Issue by MindLostGuy** [guohaoxiang/ComplexGen#8]
Hi and thank you for the great work!

To create a new dataset, I'm wondering how to sample from the B-rep surfaces (which I get from **.step** files). I've read through the codebase of **ABCDataset** and **ParseNet** but find nothing.

Hope for you rely!

**Comment by MindLostGuy** [comment]
By the way, are lines such as seam lines dismissed? 

And how to sort the patches, curves and vertices? Are there any rules? 

Hope for your reply!

**Comment by guohaoxiang** [comment]
You can find the details of pre-processing pipelines in the [supplemental material](https://haopan.github.io/data/ComplexGen_supplemental.zip) of our paper.  When sampling points on curves and patches, we firstly uniformly sample data on the parametric domain, then map them to the spatial shape:
![image](https://user-images.githubusercontent.com/29721619/216317324-635b0a3f-ac79-433f-911d-ce29c82f3a96.png)

When mentioning 'seam lines', do you mean the smooth features of the shape? They should be kept to make the input data topologically valid.

No sorting is needed.

**Comment by MindLostGuy** [comment]
I am talking about the **seam edge**: one edge is shared by a face twice. It seems violate the topology constraint (2). Here's an example:

![seam](https://user-images.githubusercontent.com/53077849/216320971-a33d3ffe-bb98-4a07-81a0-5cbcbf5bbd8d.png)

That confuses me.

By the way, when sampling uniformly on parametric domain, should the UV bounds be reset to $[0,1]^2$?

**Comment by guohaoxiang** [comment]
We removed such seam edges in our dataset.
We used the original UV bounds of the ABC dataset

**Comment by MindLostGuy** [comment]
Thanks for reply! My problems are solved.
